### ISSUE TITLE
The device does not remember last settings in "Mobile network" after shutting down or rebooting

### ISSUE THREAD

**Issue by mp107** [NotKit/droid-config-maserati#2]
After either shutting down or rebooting the device settings in the "Mobile network" section are restored to defaults.

[dmesg.txt](https://github.com/NotKit/droid-config-maserati/files/849039/dmesg.txt)
[journalctl.txt](https://github.com/NotKit/droid-config-maserati/files/849040/journalctl.txt)
[logcat.txt](https://github.com/NotKit/droid-config-maserati/files/849041/logcat.txt)

**Comment by NotKit** [comment]
See http://talk.maemo.org/showpost.php?p=1526875&postcount=59. The issue is not specific to our device and should be probably fixed upstream, but the easiest way for npw is to add this command to kickstart file when building SailfishOS image.

**Comment by mp107** [comment]
It solved the problem.
So, if there is a way to fix and incorporate the fix directly into the image, the issue seems to be fixed.
At least for our device.

EDIT: Fixed in 2.0.1.11 build.
